name = "echo"
version = "0.1.0"
authors = ["AWS s2n"]
edition = "2021"

[dependencies]
s2n-quic = { version = "1", path = "../../quic/s2n-quic" }
tokio = { version = "1", features = ["full"] }
bytes = "1"
interprocess = "1.1.1"
rand = "0.8.5"
csv = "1.1.6"

[workspace]
members = ["."]
